name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        swift-image:
          - swift:6.0-jammy
          - swift:6.1-noble
          - swift:6.2-noble
    container:
      image:  ${{ matrix.swift-image }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set DEBUG specific environment variables
      if: runner.debug == '1'
      run: |
        echo "LOG_LEVEL=trace" >> "$GITHUB_ENV"
    - name: Install zstd
      run: |
        apt-get update -y
        apt-get install -y zstd
    - name: Restore .build
      id: "restore-build"
      uses: actions/cache/restore@v4
      with:
        path: .build
        key: "${{ matrix.swift-image }}-swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
        restore-keys: "${{ matrix.swift-image }}-swiftpm-tests-build-${{ runner.os }}-"
    - name: Build
      run: swift build --build-tests --enable-code-coverage
    - name: Cache .build
      if: steps.restore-build.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: .build
        key: "${{ matrix.swift-image }}-swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
    - name: Run tests
      run: swift test --skip-build --enable-code-coverage
      env:
        PSQL_HOST: postgres
        PSQL_PORT: 5432
        PSQL_USER: postgres
        PSQL_PASSWORD: postgres
        PSQL_DATABASE: postgres
    - name: Prepare Code Coverage
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/postgres-nio-macrosPackageTests.xctest  \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: info.lcov
